### ISSUE TITLE
Cannot read properties of undefined (reading 'usec')

### ISSUE THREAD

**Issue by Para96** [ArchangelWTF/SPT.ProfileConverter#3]
Hey, thanks for making this profile converter. I really wanted to play on my profile again but it was on 3.8.3 so I wanted to convert
it and use SPT 3.9.5(installed half an hour ago).

I'm running into an issue where the tool confirms that the profile has been converted correctly. I can log in to the account on the 
launcher but when I launch the game and it loads the profile I get an error. 

![image](https://github.com/user-attachments/assets/2635b51c-ab6e-4607-adb8-e67a1087d4c1)

Any idea as to what might be causing this? 
I'm not using any mods that change items as far as I know.

In case you want to test it yourself:
Original profile:
[6630fdf70003ab033f2fa715.json](https://github.com/user-attachments/files/16500752/6630fdf70003ab033f2fa715.json)

Converted profile:
[6630fdf70003ab033f2fa715.json](https://github.com/user-attachments/files/16500743/6630fdf70003ab033f2fa715.json)

Used mods while playing both old profile and currently installed (all mods have been downloaded today, so they have the latest versions): 
- Sain
- Questing bots
- Looting bots
- Waypoints
- Swag
- Bigbrain
- Fika
- Unity toolkit (required for Sain)

**Comment by ArchangelWTF** [comment]
It's because Ref isn't added automatically to some profiles for whatever reason, I've never managed to to replicate this on my own profiles or those of my friends when we are playing together with FIKA so I didn't think of this issue as that big of a deal.

I've fixed up the profile here though: [6630fdf70003ab033f2fa715.json](https://github.com/user-attachments/files/16503990/6630fdf70003ab033f2fa715.json)

**Comment by Para96** [comment]
Damn thanks for the fast reply :o It works!!!
Ill just need to do the same for the other profiles but since I have an example of how to fix it I should be able to do it myself. You are a legend! And thanks for the work on this project.
